## Not a config, but useful for making sure all links are valid/etc. See https://github.com/gjtorikian/html-proofer
# bundle exec htmlproofer --allow_hash_href --url-ignore "/about/,/feed/,/plans/" --assume-extension --empty_alt_ignore ./_site

### Some config I'm not sure if its actually needed
twitter_username: thewoodknight
github_username:  thewoodknight

### if this isn't needed by a plugin, should be moved to a _data/social.yml format
social:
  name: The Wood Knight
  instagram: https://www.instagram.com/thewoodknight/
  twitch: https://www.twitch.tv/thewoodknight 
  twitter: https://twitter.com/thewoodknight
  youtube: https://www.youtube.com/c/PaulJenkinsTheWoodKnight
  links:
   - https://www.instagram.com/thewoodknight/
   - https://www.twitch.tv/thewoodknight 
   - https://twitter.com/thewoodknight
   - https://www.youtube.com/c/PaulJenkinsTheWoodKnight

# because american timezones strike back
future: true

# Actual config
title: The Wood Knight
author: Paul Jenkins
email: 
description: From Weekend Warrior to Wood Knight
url: "https://www.thewoodknight.com"
logo: assets/images/twklogo_150_150.png
include: ["_pages", "_redirects", "calculator", "_framework", "_bin"]
exclude:
  - .jekyll-cache

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
  - jekyll-toc
  - jekyll-category-pages
  - jekyll-purgecss
  - jekyll-seo-tag

collections:
  plans:
      output: true
      permalink: /:collection/:name

sass:
  sass_dir: _sass
  style: :compressed

# Pagination 
paginate: 13
paginate_path: /page:num/

#theme related
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
feed:
  path: /feed/index.xml

#Markdown
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: false

#jekyll-seo-tag
twitter:
  username: thewoodknight
  card: summary

#css-purge
css_dir: "/assets/css/"

#jekyllpicturetag
picture:
  ignore_missing_images: true